{{- if .Values.badges.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar.fullname" . }}-badges
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lunar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: badges
  template:
    metadata:
      {{- with .Values.badges.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lunar.labels" . | nindent 8 }}
        app.kubernetes.io/component: badges
        {{- with .Values.badges.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lunar.serviceAccountName" . }}
      {{- with .Values.badges.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.badges.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.badges.image.repository }}:{{ .Values.badges.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.badges.image.pullPolicy }}
          {{- with .Values.badges }}
          env:
            - name: BADGES_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name }}
                  key: {{ .secret.key }}
          {{- end }}
          {{- with .Values.badges.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.badges.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.badges.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.badges.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.badges.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.badges.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.badges.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}