{{- if .Values.badges.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar.fullname" . }}-badges
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.badges.service.type }}
  ports:
    - port: {{ .Values.badges.service.port }}
      targetPort: http
      protocol: TCP
      name: badges-rest
  selector:
    {{- include "lunar.selectorLabels" . | nindent 4 }}
{{- end }}