{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar.fullname" . }}-grafana
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: grafana-ui
  selector:
    {{- include "lunar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}