{{- if .Values.grafana.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lunar.fullname" . }}-grafana
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lunar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      {{- with .Values.grafana.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lunar.labels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
        {{- with .Values.grafana.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lunar.serviceAccountName" . }}
      {{- with .Values.grafana.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.grafana.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          {{- with .Values.grafana }}
          env:
            - name: POSTGRES_HOST
              value: {{ $.Values.hub.db.host | quote }}
            - name: POSTGRES_PORT
              value: {{ $.Values.hub.db.port | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.hub.db.user.secretName }}
                  key: {{ $.Values.hub.db.user.secretKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.hub.db.pass.secretName }}
                  key: {{ $.Values.hub.db.pass.secretKey }}
            - name: POSTGRES_DB
              value: {{ $.Values.hub.db.name | quote }}
            - name: LUNAR_HUB_HOST
              value: {{ include "lunar.fullname" $ }}-hub
            - name: LUNAR_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.hub.auth.secretName }}
                  key: {{ $.Values.hub.auth.secretKey }}
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .admin.user.secretName }}
                  key: {{ .admin.user.secretKey }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .admin.password.secretName }}
                  key: {{ .admin.password.secretKey }}
            - name: GF_INSTALL_PLUGINS
              value: "yesoreyeram-infinity-datasource,marcusolsson-dynamictext-panel,volkovlabs-echarts-panel"
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: "earthly-json-tree-panel"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/etc/grafana/provisioning/dashboards/home.json"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_USERS_DEFAULT_THEME
              value: "tron"
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "grafanaconThemes"
            {{- with .extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.grafana.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.grafana.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.grafana.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}