apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar.fullname" . }}-hub
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.ports.server }}
      targetPort: hub-grpc
      protocol: TCP
      name: hub-grpc
    - port: {{ .Values.hub.service.ports.webhook }}
      targetPort: hub-webhook
      protocol: TCP
      name: hub-webhook
  selector:
    {{- include "lunar.selectorLabels" . | nindent 4 }}
