{{- if .Values.hub.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lunar.fullname" . }}-hub
  labels:
    {{- include "lunar.labels" . | nindent 4 }}
  {{- with .Values.hub.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.hub.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.hub.ingress.tls }}
  tls:
    {{- range .Values.hub.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.hub.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "lunar.fullname" $ }}
                port:
                  number: {{ $.Values.hub.service.ports.server }}
          - path: /webhook
            pathType: Prefix
            backend:
              service:
                name: {{ include "lunar.fullname" $ }}
                port:
                  number: {{ $.Values.hub.service.ports.webhook }}
    {{- end }}
{{- end }}
