apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-hub.fullname" . }}-hub
  labels:
    {{- include "lunar-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.ports.server }}
      targetPort: {{ .Values.hub.ports.server }}
      protocol: TCP
      name: hub-grpc
    - port: {{ .Values.hub.service.ports.webhook }}
      targetPort: {{ .Values.hub.ports.webhook }}
      protocol: TCP
      name: hub-webhook
  selector:
    {{- include "lunar-hub.selectorLabels" . | nindent 4 }}
