apiVersion: v1
kind: Service
metadata:
  name: {{ include "lunar-hub.fullname" . }}
  labels:
    {{- include "lunar-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lunar-hub.selectorLabels" . | nindent 4 }}
